include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    avoid_print: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_const_constructors: true
    avoid_function_literals_in_foreach_calls: true
    directives_ordering: true
    lines_longer_than_80_chars: false

