name: Code Quality & Security

on:
  pull_request:
    branches: [main, develop]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze --fatal-infos
      - name: Format check
        run: dart format --output=none --set-exit-if-changed .

